{
  "default": true,
  "line-length": false,
  "no-duplicate-heading": false,
  "no-trailing-punctuation": false,
  "blanks-around-lists": false,
  "blanks-around-fences": false,
  "blanks-around-headings": false,
  "fenced-code-language": false,
  "no-emphasis-as-heading": false,
  "no-trailing-spaces": false,
  "no-multiple-blanks": false,
  "ul-indent": false,
  "list-indent": false,
  "hr-style": false,
  "no-bare-urls": false,
  "no-inline-html": false,
  "no-multiple-space-blockquote": false,
  "MD041": false,
  "MD060": false,
  "globs": ["!tests/integration/test_data/TODO.md", "!docs/archive/*.md"]
}
