{
  "default": true,
  "line-length": false,
  "no-duplicate-heading": false,
  "no-trailing-punctuation": false,
  "blanks-around-lists": false,
  "blanks-around-fences": false,
  "blanks-around-headings": false,
  "fenced-code-language": false,
  "no-emphasis-as-heading": false,
  "no-trailing-spaces": false,
  "no-multiple-blanks": false,
  "ul-indent": false,
  "list-indent": false,
  "hr-style": false,
  "no-bare-urls": false
}


